/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/abilities': RouteRecordInfo<'/abilities', '/abilities', Record<never, never>, Record<never, never>>,
    '/abilities.[id]': RouteRecordInfo<'/abilities.[id]', '/abilities/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/builder': RouteRecordInfo<'/builder', '/builder', Record<never, never>, Record<never, never>>,
    '/builder.pokemons': RouteRecordInfo<'/builder.pokemons', '/builder/pokemons', Record<never, never>, Record<never, never>>,
    '/builder.teams': RouteRecordInfo<'/builder.teams', '/builder/teams', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>>,
    '/moves': RouteRecordInfo<'/moves', '/moves', Record<never, never>, Record<never, never>>,
    '/moves.[id]': RouteRecordInfo<'/moves.[id]', '/moves/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/natures': RouteRecordInfo<'/natures', '/natures', Record<never, never>, Record<never, never>>,
    '/pokemons': RouteRecordInfo<'/pokemons', '/pokemons', Record<never, never>, Record<never, never>>,
    '/pokemons.[id]': RouteRecordInfo<'/pokemons.[id]', '/pokemons/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/types': RouteRecordInfo<'/types', '/types', Record<never, never>, Record<never, never>>,
    '/types.[id]': RouteRecordInfo<'/types.[id]', '/types/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
